# Generated by Django 3.1.1 on 2020-09-22 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200921_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
